name: Build and Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build site
      run: npm run build
      
    - name: Check build output
      run: |
        if [ ! -d "_site" ]; then
          echo "Build failed: _site directory not found"
          exit 1
        fi
        if [ ! -f "_site/index.html" ]; then
          echo "Build failed: index.html not found in _site"
          exit 1
        fi
        echo "Build successful: $(find _site -type f | wc -l) files generated"
